name: Build and Test

# Run this workflow on every push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up CMake
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: "3.20"  # Minimum version you need

      # Step 3: Install dependencies (Linux-only)
      - name: Install dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential


      - name: Install MinGW
        if: runner.os == 'Windows'
        run: choco install mingw --params "/installDir:C:\mingw" --no-progress --yes

      - name: Add MinGW to PATH
        if: runner.os == 'Windows'
        run: echo "C:\\mingw\\bin" >> $GITHUB_PATH

      - name: Configure CMake (window>
        if: runner.os == 'Windows'
        run: cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - MinGW Makefiles" -S . -B build


      - name: Configure cmake
        if: runner.os != 'Windows'
        run: cmake -S . -B build

      # Step 4: Build the project
      - name: Build
        run: |
          cmake --build build

      # Step 5: Run Tests (if any)
      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure
